name: Daily AI Post
on:
  schedule:
    - cron: '0 14 * * *'  # every day @9 AM CDT

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - run: |
          python -m venv venv
          source venv/bin/activate
          pip install transformers torch
          python generate_post.py

      - run: |
          git config user.name github-actions
          git config user.email actions@github.com
          git add posts/
          git commit -m "📝 Add daily post"
          git push
